---

- name: Docker | Install packages necessary for install Docker.
  ansible.builtin.apt: 
    pkg:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
  tags: docker

- name: Docker | Add Docker's official GPG Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: docker

- name: Docker | Set stable version repository
  ansible.builtin.apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_facts.lsb.codename }} stable"
    filename: docker
    state: present
  tags: docker

- name: Docker | Update ubuntu and repository
  ansible.builtin.apt: update_cache=yes force_apt_get=yes
  tags: docker

- name: Docker | Install Docker stable version and containerd.io
  ansible.builtin.apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    force: yes
  tags: docker

...