---

- name: Update apt-get repo and cache 
  apt: update_cache=yes force_apt_get=yes

- name: Download key vagrant.
  ansible.builtin.shell: curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -

- name: Add the vagrant apt repository
  ansible.builtin.shell: sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

- name: Update apt-get repo and cache 
  apt: update_cache=yes force_apt_get=yes

- name: Install vagrant.
  apt: 
    pkg:
    - vagrant={{ vagrant_version }}