---

- name: Install packages for install terraform.
  apt: 
    pkg:
    - gnupg
    - curl
    - software-properties-common

- name: Add HashiCopr official GPG Key
  ansible.builtin.shell: curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -

- name: Add official HashiCorp Linux repository
  ansible.builtin.shell: sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

- name: Update ubuntu and repository
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Install package terraform
  apt: 
    pkg:
    - terraform

...