---

- name: Update apt-get repo and cache 
  apt: update_cache=yes force_apt_get=yes

- name: Install packages necessary for install Kubectl.
  apt: 
    pkg:
    - ca-certificates
    - curl
    - apt-transport-https

- name: Download the Googl Cloud public sining Key.
  ansible.builtin.shell: sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: Add the kubernetes apt repository
  ansible.builtin.shell: echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list

- name: Update apt-get repo and cache 
  apt: update_cache=yes force_apt_get=yes

- name: Install Kubectl.
  apt: 
    pkg:
    - kubectl={{ kubectl_version }}