---

- name: Vagrant | Update apt-get repo and cache 
  apt: update_cache=yes force_apt_get=yes
  tags: vagrant

- name: Vagrant | Download key vagrant.
  ansible.builtin.apt_key: 
    url: https://apt.releases.hashicorp.com/gpg
    state: present
  tags: vagrant

- name: Vagrant | Add official HashiCorp Linux repository
  ansible.builtin.apt_repository:
    repo: "deb https://apt.releases.hashicorp.com {{ ansible_facts.lsb.codename }} main"
    filename: vagrant
    state: present
  tags: vagrant

- name: Vagrant | Update apt-get repo and cache 
  apt: update_cache=yes force_apt_get=yes
  tags: vagrant

- name: Vagrant | Install vagrant.
  apt: 
    pkg:
    - vagrant={{ vagrant_version }}
    force: yes
  tags: vagrant