---

- name: Terraform | Install packages for install terraform.
  ansible.builtin.apt: 
    pkg:
    - gnupg
    - curl
    - software-properties-common
  tags: terraform

- name: Terraform | Add HashiCopr official GPG Key
  ansible.builtin.apt_key: 
    url: https://apt.releases.hashicorp.com/gpg 
    state: present
  tags: terraform

- name: Terraform | Add official HashiCorp Linux repository
  ansible.builtin.apt_repository:
    repo: "deb https://apt.releases.hashicorp.com {{ ansible_facts.lsb.codename }} main"
    filename: terraform
    state: present
  tags: terraform

- name: Terraform | Update ubuntu and repository
  ansible.builtin.apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  tags: terraform

- name: Terraform | Install package terraform
  ansible.builtin.apt: 
    pkg:
    - terraform
    force: yes
  tags: terraform

...