---

- name: Helm | Update apt-get repo and cache 
  ansible.builtin.apt: update_cache=yes force_apt_get=yes
  tags: helm

- name: Helm | Install packages necessary for install Helm.
  ansible.builtin.apt: 
    pkg:
    - curl
    - apt-transport-https
  tags: helm

- name: Helm | Download key helm.
  ansible.builtin.apt_key: 
    url: https://baltocdn.com/helm/signing.asc
    state: present
  tags: helm

- name: Helm | Add the helm apt repository
  ansible.builtin.apt_repository:
    repo: "deb https://baltocdn.com/helm/stable/debian/ all main"
    filename: helm
    state: present
  tags: helm

- name: Helm | Update apt-get repo and cache 
  ansible.builtin.apt: update_cache=yes force_apt_get=yes
  tags: helm

- name: Helm | Install helm.
  ansible.builtin.apt: 
    pkg:
    - helm={{ helm_version }}
  tags: helm