---

- name: Kind | Download kind
  ansible.builtin.shell: curl -Lo ./kind https://kind.sigs.k8s.io/dl/{{ kind_version }}/kind-linux-amd64
  tags: kind

- name: Kind | Giving permission to the kind executable
  ansible.builtin.shell: chmod +x ./kind
  tags: kind

- name: Kind | Moving kind to bin directory
  ansible.builtin.shell: mv ./kind /usr/local/bin
  tags: kind
  