---

- name: Kubectl | Update apt-get repo and cache 
  apt: update_cache=yes force_apt_get=yes
  tags: kubectl

- name: Kubectl | Install packages necessary for install Kubectl.
  apt: 
    pkg:
    - ca-certificates
    - curl
    - apt-transport-https
  tags: kubectl

- name: Kubectl | Download the Google Cloud public sining Key.
  ansible.builtin.apt_key: 
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg
    state: present
  tags: kubectl

- name: Kubectl | Add the kubernetes apt repository
  ansible.builtin.apt_repository: 
    repo: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
  tags: kubectl

- name: Kubectl | Update apt-get repo and cache 
  apt: update_cache=yes force_apt_get=yes
  tags: kubectl

- name: Kubectl | Install Kubectl.
  apt: 
    pkg:
    - kubectl={{ kubectl_version }}
    force: yes
  tags: kubectl
