---

- name: Update apt-get repo and cache 
  apt: update_cache=yes force_apt_get=yes

- name: Install packages necessary for install Helm.
  apt: 
    pkg:
    - curl
    - apt-transport-https

- name: Download key helm.
  ansible.builtin.shell: curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -

- name: Add the helm apt repository
  ansible.builtin.shell: echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list

- name: Update apt-get repo and cache 
  apt: update_cache=yes force_apt_get=yes

- name: Install helm.
  apt: 
    pkg:
    - helm={{ helm_version }}