---
# tasks file for role-install-packages


- include: update-upgrade-ubuntu.yml
- include: install-docker-ubuntu.yml
- include: install-terraform-ubuntu.yml
- include: install-kubectl-ubuntu.yml
- include: install-kind-ubuntu.yml
- include: install-vagrant-ubuntu.yml
...