---
# tasks file for role-install-packages

- name: Ubuntu | update and install packages.
  include_tasks: update-ubuntu.yml
  tags: 
    - update-ubuntu

- name: Ubuntu | upgrade 
  include_tasks: upgrade-ubuntu.yml
  tags: 
    - upgrade-ubuntu

- name: Ubuntu | Install packages
  include_tasks: install-packages-ubuntu.yml
  tags:
    - packages-ubuntu

- name: Docker | Add repository and install
  include_tasks: install-docker-ubuntu.yml
  tags:
    - docker

- name: Docker compose | Add repository and install
  include_tasks: install-docker-compose-ubuntu.yml
  tags:
    - docker-compose

- name: Terraform | Add repository and install
  include_tasks: install-terraform-ubuntu.yml
  tags: 
    - terraform

- name: Kubectl | Add repository and install
  include_tasks: install-kubectl-ubuntu.yml
  tags: 
    - kubectl

- name: Kind | Add repository and moving binary
  include_tasks: install-kind-ubuntu.yml
  tags: 
    - kind

- name: Helm | Add repository and install
  include_tasks: install-helm-ubuntu.yml
  tags: 
    - helm

- name: Vagrant | Add repository and install
  include_tasks: install-vagrant-ubuntu.yml
  tags: 
    - vagrant

- name: Ubuntu | Remove cache 
  include_tasks: remove-cache-ubuntu.yml
  tags: 
    - remove-cache-ubuntu
...