---

- name: Ubuntu | Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: yes
  tags: remove-cache-ubuntu

- name: Ubuntu | Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: yes
  tags: remove-cache-ubuntu


...